# -*- mode: ruby -*-
# vi: set ft=ruby :


# Faut faire une machine msimaoS 
# Avec 3 app quon peux acceder avec ip + host 
# exmple : 192.168.56.110 in their web browser with the HOST app1.com,
# app1 none
# app2 3 replica
# app3 by default

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "kdurouxS" do |s|
    s.vm.hostname = "kdurouxS"
    s.vm.network "private_network", ip: "192.168.56.110"

    # s.vm.synced_folder ".", "/vagrant", type: "9p", disabled: false, accessmode: "mapped"

    s.vm.provider :libvirt do |v|
      v.driver = "qemu"
      v.cpu_mode = "host-model"
      v.cpus = 4
      v.memory = 4048
      v.machine_type = "q35"
    end
    s.vm.provision "shell", path:"scripts/install-server.sh" 
  end
end
