#-*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "conf/variables"

Vagrant.configure("2") do |config|
  config.vm.box = OS

  config.vm.define SERVER_NAME do |s|
    s.vm.hostname = SERVER_NAME
    s.vm.network "private_network", ip: SERVER_IP

    s.vm.provider :libvirt do |v|
      v.driver = "qemu"
      v.cpu_mode = "host-model"
      v.cpus = 1
      v.memory = 1024
      v.machine_type = "q35"
    end


    s.vm.provision "shell", path:"scripts/install-server.sh" 
  end


  config.vm.define WORKER_NAME do |sw|
    sw.vm.hostname = WORKER_NAME
    sw.vm.network "private_network", ip: WORKER_IP

    sw.vm.provider :libvirt do |v|
      v.driver = "qemu"
      v.cpu_mode = "host-model"
      v.cpus = 1
      v.memory = 1024
    end

    sw.vm.provision "shell", path: "scripts/install-worker.sh" 
  end
end
