apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app
  namespace: argocd
spec:
  project: default
  source:
    #a remplacer par le gitlab
    repoURL: 'https://github.com/kix300/42_IOT.git'
    targetRevision: HEAD
    path: 'bonus'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
