   apiVersion: argoproj.io/v1alpha1
   kind: Application
   metadata:
     name: gitlab
     namespace: argocd
   spec:
     project: default
     source:
       chart: gitlab
       repoURL: https://charts.gitlab.io/
       targetRevision: 7.6.0
       helm:
         valuesObject:
           global:
             hosts:
               domain: kixlab.com
               hostSuffix: "" 
             ingress:
               configureCertmanager: false
           certmanager:
             install: false
           nginx-ingress:
             enabled: false
           gitlab:
             webservice:
               service:
                 type: NodePort
                 nodePort: 30082
             gitaly:
               persistence:
                 enabled: true
                 size: 10Gi
             postgresql:
               persistence:
                 enabled: true
                 size: 10Gi
             redis:
               persistence:
                 enabled: true
                 size: 5Gi
           registry:
             enabled: false
           prometheus:
             install: false
     destination:
       server: 'https://kubernetes.default.svc'
       namespace: gitlab  
     syncPolicy:
       automated:
         selfHeal: true
         prune: true
   
